// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoSophos.Infrastructure.Data;

#nullable disable

namespace ProyectoSophos.Infrastructure.Migrations
{
    [DbContext(typeof(EmpresaRandomDbContext))]
    partial class EmpresaRandomDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoSophos.Core.Entities.Price", b =>
                {
                    b.Property<string>("IdPrice")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id_price");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("price");

                    b.Property<string>("IdVideoGames")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id_video_games");

                    b.Property<decimal?>("PricePenalty")
                        .HasColumnType("decimal(6, 2)")
                        .HasColumnName("Price_penalty");

                    b.HasKey("IdPrice")
                        .HasName("PK__price_da__D8A23E836CA62DF3");

                    b.HasIndex("IdVideoGames");

                    b.ToTable("price_data", (string)null);
                });

            modelBuilder.Entity("ProyectoSophos.Core.Entities.Rental", b =>
                {
                    b.Property<string>("IdRent")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id_rent");

                    b.Property<string>("IdUserRental")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id_user_rental");

                    b.Property<string>("IdVideoGamesRental")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id_video_games_rental");

                    b.Property<DateTime?>("RentalDate")
                        .HasColumnType("date")
                        .HasColumnName("retal_date");

                    b.Property<DateTime?>("RentalEndDate")
                        .HasColumnType("date")
                        .HasColumnName("rental_end_date");

                    b.HasKey("IdRent")
                        .HasName("PK__rental_d__0F4BF3B0E8DAAD5F");

                    b.HasIndex("IdUserRental");

                    b.HasIndex("IdVideoGamesRental");

                    b.ToTable("rental_data", (string)null);
                });

            modelBuilder.Entity("ProyectoSophos.Core.Entities.User", b =>
                {
                    b.Property<string>("IdUser")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id_user");

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("gender");

                    b.Property<string>("Identification")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("identification");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("postal_code");

                    b.HasKey("IdUser")
                        .HasName("PK__users_da__D2D14637734108DF");

                    b.ToTable("users_data", (string)null);
                });

            modelBuilder.Entity("ProyectoSophos.Core.Entities.VideoGame", b =>
                {
                    b.Property<string>("IdGame")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("id_game");

                    b.Property<string>("Brand")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("brand");

                    b.Property<string>("CoverPage")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cover_page");

                    b.Property<string>("Director")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("director");

                    b.Property<string>("MainCharacter")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("main_character");

                    b.Property<string>("NameGame")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name_game");

                    b.Property<string>("Platforms")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("platforms");

                    b.Property<string>("Producer")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("producer");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.HasKey("IdGame")
                        .HasName("PK__video_ga__0E819B2C2A86159C");

                    b.ToTable("video_game_data", (string)null);
                });

            modelBuilder.Entity("ProyectoSophos.Core.Entities.Price", b =>
                {
                    b.HasOne("ProyectoSophos.Core.Entities.VideoGame", "IdVideoGamesNavigation")
                        .WithMany("PriceData")
                        .HasForeignKey("IdVideoGames")
                        .HasConstraintName("fk_video_game");

                    b.Navigation("IdVideoGamesNavigation");
                });

            modelBuilder.Entity("ProyectoSophos.Core.Entities.Rental", b =>
                {
                    b.HasOne("ProyectoSophos.Core.Entities.User", "IdUserRentalNavigation")
                        .WithMany("RentalData")
                        .HasForeignKey("IdUserRental")
                        .HasConstraintName("fk_usesr_rental");

                    b.HasOne("ProyectoSophos.Core.Entities.VideoGame", "IdVideoGamesRentalNavigation")
                        .WithMany("RentalData")
                        .HasForeignKey("IdVideoGamesRental")
                        .HasConstraintName("fk_video_games_rental");

                    b.Navigation("IdUserRentalNavigation");

                    b.Navigation("IdVideoGamesRentalNavigation");
                });

            modelBuilder.Entity("ProyectoSophos.Core.Entities.User", b =>
                {
                    b.Navigation("RentalData");
                });

            modelBuilder.Entity("ProyectoSophos.Core.Entities.VideoGame", b =>
                {
                    b.Navigation("PriceData");

                    b.Navigation("RentalData");
                });
#pragma warning restore 612, 618
        }
    }
}
